config/routes.rb
Rails.application.routes.draw do
  resources :assets
  devise_for :users
  root 'home#index'
  get 'home/lookup'
  post "/home/lookup" => 'home/lookup'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :assets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  require 'net/http'
  require 'json'

  # GET /assets
  # GET /assets.json
  def index
    @profit_loss = 0
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_coin = JSON.parse(@response)

    @assets = Asset.all
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @user = current_user
    @asset = @user.assets.new
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets
  # POST /assets.json
  def create
    @user = current_user
    @asset = @user.assets.build(asset_params)
    
    respond_to do |format|
      if @asset.save
        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
        format.json { render :show, status: :created, location: @asset }
      else
        format.html { render :new }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @asset }
      else
        format.html { render :edit }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to assets_url, notice: 'Asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'net/http'
  require 'json'
  
  def index

    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
    @my_coins = ["BTC", "EOS", "XRP", "ADA", "STEEM",]
  end

  def lookup
    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_coin = JSON.parse(@response)
    
    @symbol = params[:sym]

    if @symbol
      @symbol = @symbol.upcase
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/assets/_form.html.erb
<%= form_with(model: asset, local: true) do |form| %>
  <% if asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :cost_per %>
    <%= form.text_field :cost_per, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :amount_owned %>
    <%= form.text_field :amount_owned, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success mt-3" %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<h1>Editing Asset</h1>

<%= render 'form', asset: @asset %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<h1>Assets</h1>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Current Price</th>
      <th>Rank</th>
      <th>Current Value</th>
      <th>Total Paid</th>
      <th>Profit / Loss</th>
      <th>Cost Paid Per</th>
      <th>Amount owned</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>              
        <% for x in @lookup_coin %>
          <% if asset.symbol == x["symbol"] %>
          <td> <%= x["name"] %> <small>(<%= asset.symbol %>)</small></td>
          <td> $<%= x["price_usd"] %></td>
          <td> <%= x["rank"] %></td>
          <td> $<%= x["price_usd"].to_d * asset.amount_owned %></td>
          <td> $<%= asset.cost_per * asset.amount_owned %> </td>
          <td> $<%= (x["price_usd"].to_d * asset.amount_owned) - (asset.cost_per * asset.amount_owned )  %> </td>
          <% @profit_loss += (x["price_usd"].to_d * asset.amount_owned) - (asset.cost_per * asset.amount_owned )  %>
          <% end %>
        <% end %>
        
        <td>$<%= asset.cost_per %></td>
        <td><%= asset.amount_owned %></td>
        <td><%= link_to 'Show', asset %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>Total Profit/Loss: <%= number_to_currency(@profit_loss) %></p>

<%= link_to 'New Asset', new_asset_path, class: "btn btn-primary" %>

app/views/assets/new.html.erb
<h1>New Asset</h1>

<%= render 'form', asset: @asset %>

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<p>
  <strong>Symbol:</strong>
  <%= @asset.symbol %>
</p>

<p>
  <strong>Cost per:</strong>
  <%= @asset.cost_per %>
</p>

<p>
  <strong>Amount owned:</strong>
  <%= @asset.amount_owned %>
</p>

<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>

app/views/home/index.html.erb
<% for x in @coins %>
  <% for coin in @my_coins %>
    <% if coin == x["symbol"] %>
      Name: <%= x["name"] %>: 
      Price: <%= x["price_usd"] %>
      Rank: <%= x["rank"] %>
    <% end %>
  <% end %>
<% end %>

app/views/home/lookup.html.erb
<h3>Cryptocurrency Lookup</h3>

<%= form_tag home_lookup_path, :method => 'POST' do %>
  <%= text_field_tag 'sym', nil, placeholder: 'Enter Symbol', size: 50 %>
  <%= submit_tag 'Lookup'%>
<% end %>



<% if @symbol %>
  <% for x in @lookup_coin %>
    <% if @symbol == x["symbol"] %>
      Name: <%= x["name"] %>: 
      Price: <%= x["price_usd"] %>
      Rank: <%= x["rank"] %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible">
    <button class="close" data-dismiss="alert">
      <i class="glyphicon glyphicon-remove-circle"></i>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible">
    <button class="close" data-dismiss="alert">
      <i class="fa fa-window-close"></i>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <span class="navbar-brand" href="#">Cryptofolio</span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <div class="navbar-nav mr-auto"></div>
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%= link_to root_path, class: "nav-link" do %>
        Home <span class="sr-only">(current)</span>
      <% end %>
      </li>
      <li class="nav-item">
        <%= link_to 'Lookup', home_lookup_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
      <li class="nav-item">
        <%= link_to 'My Assets', assets_path, class: "nav-link" %>
      </li>
        <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Sign in', user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Register', new_user_registration_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptofolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
  </body>
</html>